name: Build Deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  build_on_mac:
    if: github.event.pull_request.merged
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.ADMIN_GH_TOKEN }}
      CSC_IDENTITY_AUTO_DISCOVERY: true
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS : ${{ secrets.APPLEIDPASS }}
      CSC_LINK : ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD : ${{ secrets.CSC_KEY_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-node@master
      with:
        node-version: 16.10
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install dependencies from yarn
      run: yarn install --network-timeout 1000000
    - name: Build ON MacOs
      run: yarn dist
  build_on_win:
    if: github.event.pull_request.merged
    runs-on: windows-2016
    env:
      GH_TOKEN: ${{ secrets.ADMIN_GH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main        
    - uses: actions/setup-node@master
      with:
        node-version: 16.10
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install dependencies from yarn
      run: yarn install --network-timeout 1000000
    - name: Build On win
      run: yarn dist