name: Build Deploy
on:
  push:
    tags : [ios]
    branches:
      - main
jobs:
  build_on_mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.ADMIN_GH_TOKEN }}
      CSC_IDENTITY_AUTO_DISCOVERY: true
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS : ${{ secrets.APPLEIDPASS }}
      CSC_LINK : ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD : ${{ secrets.CSC_KEY_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-node@master
      with:
        node-version: 16.10
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install dependencies from yarn
      run: yarn install --network-timeout 1000000
    - name: Build ON MacOs
      run: yarn dist