# name of your github action
name: CI
# this will help you specify where to run 
on:
  push:
    branches:
    # this will run on the electron branch
      - main
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
      with:
        ref: main
    - uses: actions/setup-node@master
      with:
        node-version: 16.10
    - name: Install dependencies
      run: npm install
    - name: Build ON MacOs
      run: npm run publish
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: main        
    - uses: actions/setup-node@master
      with:
        node-version: 16.10
    - name: see directory
      run: ls
